name: postfetcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  connectivity_plus: ^2.1.0
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutx: ^0.2.0-rc.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  path_drawing: ^1.0.0
  lottie: ^3.3.1
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^1.1.3
  mocktail: ^1.0.4
  hive_test: ^1.0.1
  http_mock_adapter: ^0.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
